spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/remitk_registry
    username: remitk
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations