spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/remitk_registry}
    username: ${DB_USERNAME:remitk}
    password: ${DB_PASSWORD:remitk}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations